#!/bin/sh

set -e

script/bootstrap

bundle exec jekyll doctor

bundle exec rake test

if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
	bundle exec rake prepare
	bundle exec rake deploy
fi
